ZTech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import z_tech.views
from z_tech.views import TechListView

urlpatterns = [
    path('', include('main.urls')),
    path('mypage', TechListView.as_view(), name='home'),
    path('mypages', z_tech.views.list_tech, name='home'),
    path('z_tech/', include('z_tech.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('inner/', views.inner, name='inner'),
    path('saving/', views.saving, name='saving'),
    path('investment/', views.investment, name='investment'),
]

z_tech/urls.py
from django.urls import path

from z_tech import views
from z_tech.views import TechCreateView, TechUpdateView

app_name = 'z_tech'

urlpatterns = [
    path('list2/', views.list_tech, name='list'),
    path('add/', TechCreateView.as_view(), name='add'),  # bookmark:add
    path('detail2/<int:pk>/', views.detail_tech, name='detail'),   # bookmark:detail
    path('edit/<int:pk>/', TechUpdateView.as_view(), name='edit'),      # bookmark:edit
    path('delete/<int:pk>/', views.delete_tech, name='delete'), # bookmark:delete
]

z_tech/models.py
from django.db import models
from django.shortcuts import resolve_url

from accounts.models import Profile


class Tech(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=10)
    updated_at = models.DateTimeField(auto_now=True)
    url = models.URLField()

    # 연도별 로드맵
    year = models.PositiveIntegerField(default=0)
    # 올해 모은 돈
    money = models.PositiveIntegerField(default=0)
    # 올해 목표 저축액
    goal = models.PositiveIntegerField(default=0)

    # 진행도
    Percent = (
        ('zero', '0'),
        ('one', '10'),
        ('two', '20'),
        ('three', '30'),
        ('four', '40'),
        ('five', '50'),
        ('six', '60'),
        ('seven', '70'),
        ('eight', '80'),
        ('nine', '90'),
        ('ten', '100'),
    )

    percent = models.CharField(max_length=30, choices=Percent, default='zero',)

    # 돈을 모아야 하는 이유
    reason = models.CharField(max_length=100)

    # 돈을 어떻게 벌고 있는지
    # 매달 들어오는 돈
    deposit = models.PositiveIntegerField(default=0)
    # 현재까지 번 돈
    gather = models.PositiveIntegerField(default=0)
    # 올해 예상 수입
    expectation = models.PositiveIntegerField(default=0)

    # 수익 타입
    Type = (
        ('fixed', '고정 수입'),
        ('non-fixed', '비고정 수입'),
        ('interest', '이자'),
        ('dividend', '배당금'),
    )

    type = models.CharField(max_length=30, choices=Type, default='fixed',)

    # 지출
    item = models.CharField(max_length=10)
    # 지출 금액
    spending = models.PositiveIntegerField(default=0)

    # 지출 태그
    Tag = (
        ('purpose', '목적성 저축'),
        ('housing', '주거비'),
        ('fixed-expenses', '고정 지출'),
        ('variable-spending', '비고정 지출'),
    )

    tag = models.CharField(max_length=30, choices=Tag, default='purpose',)

    def __str__(self):
        return f'{self.name} : {self.url}'

    def get_absolute_url(self):
        return resolve_url('z_tech:detail', pk=self.pk)

z_tech/forms.py
from django import forms

from z_tech.models import Tech

class TechCreationForm(forms.ModelForm):
    url = forms.CharField(label='링크', widget=forms.TextInput)

    class Meta:
        model = Tech
        fields = ['name', 'url']

    def clean_url(self):
        url = self.cleaned_data.get('url')  # url 가져오자
        if not (url.startswith('http://') or url.startswith('https://')):  # 만약 http:// 나 https://가 없으면,
            url = 'https://' + url  # https:// 추가하자
        return url

    def save(self, commit=True):
        new_tech = Tech.objects.create(
            name=self.cleaned_data.get('name'),  # 사용자가 입력한 내용을 clean_name()하고 깨끗해진 것 가져오자
            url=self.cleaned_data.get('url'),  # 사용자가 입력한 내용을 clean_url()하고 깨끗해진 것 가져오자
        )
        return new_tech


class TechChangeForm(forms.ModelForm):
    class Meta:
        model = Tech
        fields = ['name', 'url']

z_tech/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from accounts.models import Profile
from z_tech.forms import TechCreationForm, TechChangeForm
from z_tech.models import Tech


# class TechListView(ListView):
#     model = Tech
#
#     def get_queryset(self):
#         user = self.request.user
#         if user.is_authenticated:  # 로그인 하면, 로그인한 사용자의 북마크만 보이자
#             profile = Profile.objects.get(user=user)  # user -> profile
#             tech_list = Tech.objects.filter(profile=profile)  # profile -> bookmark_list
#         else:  # 로그인 안하면,
#             tech_list = Tech.objects.none()  # 북마크 보이지 말자
#         return tech_list

class TechCreateView(LoginRequiredMixin, CreateView):
    model = Tech
    fields = ['profile', 'name', 'url', 'year']  # '__all__'
    template_name_suffix = '_create'  # bookmark_form.html -> bookmark_create.html
    success_url = reverse_lazy('z_tech:list')

    def get_initial(self):
        user = self.request.user
        profile = Profile.objects.get(user=user)
        return {'profile': profile}


class TechDetailView(LoginRequiredMixin, DetailView):
    model = Tech


class TechUpdateView(LoginRequiredMixin, UpdateView):
    model = Tech
    fields = ['name', 'url', 'year']  # '__all__'
    template_name_suffix = '_update'  # bookmark_update.html

class TechDeleteView(LoginRequiredMixin, DeleteView):
    model = Tech
    success_url = reverse_lazy('z_tech:list')


def list_tech(request):
    # 로그인 사용자 확인하자
    user = request.user
    if user.is_authenticated:  # 로그인 되어있으면
        profile = Profile.objects.get(user=user)
        tech_list = Tech.objects.filter(profile=profile)  # 그 사용자의 북마크 가져오자
    else:  # 로그인 안되어 있으면
        tech_list = Tech.objects.none()  # 북마크 없는것 가져오자

    return render(request, 'z_tech/tech_list.html', {'tech_list': tech_list})


def detail_tech(request, pk):
    tech = Tech.objects.get(pk=pk)
    return render(request, 'z_tech/tech_detail.html', {'tech': tech})


@login_required
def delete_tech(request, pk):
    if request.method == 'POST':  # 삭제 버튼 눌렀을 때
        tech = Tech.objects.get(pk=pk)
        tech.delete()  # DELETE FROM table WHERE 조건
        return redirect('z_tech:list')
    else:  # 처음 bookmark_delete.html 요청
        tech = Tech.objects.get(pk=pk)
        return render(request, 'z_tech/tech_confirm_delete.html', {'tech': tech})


@login_required
def create_tech(request):
    if request.method == 'POST':  # 사용자가 입력하고 버튼 눌렀을 때
        form = TechCreationForm(request.POST)  # form 가져오자
        if form.is_valid():  # is_valid()
            new_tech = form.save(commit=False)  # new_bookmark 생성하자(name, url)
            new_tech.profile = Profile.objects.get(user=request.user)  # new_bookmark에 profile 추가하자
            new_tech.save()
            return redirect('z_tech:list')  # bookmark:list 이동하자
    else:  # 빈 폼
        form = TechCreationForm()
    return render(request, 'z_tech/tech_create.html', {'form': form})


@login_required
def modify_tech(request, pk):
    if request.method == 'POST':
        form = TechChangeForm(request.POST)  # form 가져오자
        if form.is_valid():  # is_valid()
            tech = Tech.objects.get(pk=pk)  # pk에 해당하는 bookmark 가져오자
            tech.name = form.cleaned_data.get('name')  # 사용자가 입력한 name set
            tech.url = form.cleaned_data.get('url')  # 사용자가 입력한 url set
            tech.save()
            return redirect('z_tech:list')  # bookmark:list로 이동하자
    else:
        tech = Tech.objects.get(pk=pk)  # pk에 해당하는 bookmark 정보 가져오자
        form = TechChangeForm(instance=tech)  # bookmark 정보 넣은 form
    return render(request, 'z_tech/tech_update.html', {'form': form})

z_tech/templates/z_tech/tech_confirm_delete.html
{% extends 'base.html' %}

{% block title %}delete Tech{% endblock %}

{% block content %}
    <div style="margin-top: 85px">
        <form action="" method="post">
            {% csrf_token %}
            <div class="alert alert-danger">
                너 북마크 {{ tech }} 진짜 지울거야?
            </div>
            <input type="submit" value="진짜 삭제" class="btn btn-danger">
            <input type="button" value="지우지마" onclick="history.back();" class="btn btn-light">
        </form>
    </div>

{% endblock %}

z_tech/templates/z_tech/tech_create.html
{% extends 'base.html' %}

{% block title %}Add Tech{% endblock %}

{% block content %}
    <div style="margin-top: 85px;">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.profile.as_hidden }}
            <p>{{ form.name.label_tag }} {{ form.name }}</p>
            <p>{{ form.url.label_tag }} {{ form.url }}</p>

            <p>sadf {{ form.year }}</p>
            <input type="submit" value="Add" class="btn btn-success">
        </form>
    </div>

{% endblock %}

z_tech/templates/z_tech/tech_detail.html
{% extends 'base.html' %}

{% block title %}Tech Detail{% endblock %}

{% block content %}
    <div style="margin-top: 85px;">
        <h1>{{ tech.name }}</h1>
        <a href="{{ tech.url }}">{{ tech.url }}</a>
        <a href="{% url 'z_tech:list' %}" class="btn btn-warning">Go to Tech List</a>
    </div>

{% endblock %}

z_tech/templates/z_tech/tech_list.html
{% extends 'base.html' %}

{% block title %}Ztech List{% endblock %}

{% block content %}
<div class="btn-group" style="margin-top: 85px">
    <a href="{% url 'z_tech:add' %}" class="btn btn-success">Add Tech</a>
</div>
<table class="table">
    <thead>
    <tr>
        <th>#</th>
        <th>Scenario Name</th>
        <th>URL</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
    {% for tech in tech_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'z_tech:detail' pk=tech.pk %}">{{ tech.name }}</a></td>
            <td><a href="{{ tech.url }}">{{ tech.url }}</a></td>
            <td><a href="{% url 'z_tech:edit' pk=tech.pk %}" class="btn btn-primary btn-sm">Edit</a></td>
            <td><a href="{% url 'z_tech:delete' pk=tech.pk %}" class="btn btn-danger btn-sm">Delete</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

z_tech/templates/z_tech/tech_update.html
{% extends 'base.html' %}

{% block title %}edit ZTech{% endblock %}

{% block content %}
    <div style="margin-top: 85px;">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_ul }}
            <input type="submit" value="Edit" class="btn btn-primary">
        </form>
    </div>

{% endblock %}