ZTech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import z_tech.views
from z_tech.views import TechListView

urlpatterns = [
    path('', include('main.urls')),
    path('mypage', TechListView.as_view(), name='home'),
    path('mypages', z_tech.views.list_tech, name='home'),
    path('z_tech/', include('z_tech.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),     #accounts:register
    path('login/', views.my_login, name='login'),
    path('logout/', views.my_logout, name='logout'),
]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('inner/', views.inner, name='inner'),
    path('saving/', views.saving, name='saving'),
    path('investment/', views.investment, name='investment'),
]

z_tech/urls.py
from django.urls import path

from z_tech import views
from z_tech.views import TechCreateView, TechUpdateView

app_name = 'z_tech'

urlpatterns = [
    path('list2/', views.list_tech, name='list'),
    path('add/', TechCreateView.as_view(), name='add'),  # bookmark:add
    path('detail2/<int:pk>/', views.detail_tech, name='detail'),   # bookmark:detail
    path('edit/<int:pk>/', TechUpdateView.as_view(), name='edit'),      # bookmark:edit
    path('delete/<int:pk>/', views.delete_tech, name='delete'), # bookmark:delete
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

      <meta content="width=device-width, initial-scale=1.0" name="viewport">

      <title>Inner Page - Butterfly Bootstrap Template</title>
      <meta content="" name="description">
      <meta content="" name="keywords">

      <!-- Favicons -->
      <link href="/static/img/favicon.png" rel="icon">
      <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">

      <!-- Google Fonts -->
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Dosis:300,400,500,,600,700,700i|Lato:300,300i,400,400i,700,700i" rel="stylesheet">

      <!-- Vendor CSS Files -->
      <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
      <link href="/static/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
      <link href="/static/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
      <link href="/static/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
      <link href="/static/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

      <!-- Template Main CSS File -->
      <link href="/static/css/style.css" rel="stylesheet">
</head>
<body>
<!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="{% url 'main:index' %}" class="logo">
          Z-Tech
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'main:index' %}#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'main:index' %}#about">About</a></li>
        <li class="dropdown"><a href="{% url 'main:inner' %}"><span>Z-Tech</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="{% url 'main:inner' %}">Z-Tech</a></li>
              <li class="dropdown"><a href="{% url 'main:saving' %}"><span>저축 상품</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="{% url 'main:saving' %}">예·적금 상품</a></li>
                  <li><a href="{% url 'main:saving' %}">주택 청약 종합 저축</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="{% url 'main:investment' %}"><span>투자 상품</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="{% url 'main:investment' %}">CMA</a></li>
                  <li><a href="{% url 'main:investment' %}">펀드</a></li>
                  <li><a href="{% url 'main:investment' %}">주식</a></li>
                </ul>
              </li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="{% url 'main:index' %}#services">Services</a></li>
          <li><a class="nav-link scrollto " href="{% url 'main:index' %}#portfolio">Recommend</a></li>
          <li><a class="nav-link scrollto" href="{% url 'main:index' %}#team">Made</a></li>
            {% if user.is_authenticated %}
                <li><a class="nav-link scrollto" href="{% url 'z_tech:list' %}">MyPage</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}">Logout</a></li>
            {% else %}
              <li><a class="nav-link scrollto" href="{% url 'accounts:register' %}">Register</a></li>
              <li><a class="nav-link scrollto" href="{% url 'accounts:login' %}">Login</a></li>
            {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

    {% block content %}
    {% endblock %}

<!-- ======= Footer ======= -->
  <footer id="footer" class="fixed-bottom">
    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>Butterfly</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer>
  <!-- End Footer -->

    <!-- Vendor JS Files -->
      <script src="/static/vendor/purecounter/purecounter.js"></script>
      <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
      <script src="/static/vendor/glightbox/js/glightbox.min.js"></script>
      <script src="/static/vendor/isotope-layout/isotope.pkgd.min.js"></script>
      <script src="/static/vendor/swiper/swiper-bundle.min.js"></script>
      <script src="/static/vendor/php-email-form/validate.js"></script>

      <!-- Template Main JS File -->
      <script src="/static/js/main.js"></script>
</body>
</html>